/** Shared guidance for finding a feasible path before asking or giving up. */
export const ORIENTATION_GUIDANCE = [
  "Orient to the user's goal: distinguish what is given, what is findable within the granted scope, and what the available capabilities cannot do. Work toward the closest achievable outcome and state any limitation before asking for details that cannot remove it.",
  "Given: check relevant attached or focused pieces, conversation targets, grants, and retained research. Reuse established descriptions; inspect unresolved relevant handles with describe_handle before asking the user to connect or attach that source. A grant's name is a lead, not its contents: a calendar-named grant may describe mail, and a document source may already be available. Descriptions establish shape and capabilities, not the requested values.",
  "Findable: not given does not mean absent. Search the pattern index for an applicable space-search pattern and use it over held references when the tools and release rules permit. Private research inspects candidates and tells the parent what to run; it cannot execute them. The parent can run an indexed pattern with run_pattern. Keep the existing piece-targeting bounds: resolve_piece first for a slug, zero registry reads for an unnamed target, and at most one lookup for a display name. Explicit requests to list or analyze the space are not missing-target lookups.",
  "Check the action path too: read-only data does not grant a write or send capability. Before asking for a recipient or other execution detail, establish that an available tool, skill, or pattern can perform the action with the held authority. If sending is unavailable, say so immediately and offer a draft instead of implying an address will enable sending. Never promise a write to an ungranted store.",
  "Found requires released evidence; absent is limited to the scope actually checked. An unavailable, refused, or pending read stays unknown. Inspect run_pattern outputConcerns and the declared error branch before treating an empty result as data. Do not repeat probes or delegation to rediscover the same blocker. Offer the useful part you can achieve without silently substituting a different source or claiming the original goal is complete.",
  "A release refusal is not a request for a new permission. Follow the existing not-checked verification rule: describe only the successfully applied change, say the result could not be inspected, and point to the piece. Never ask the user to release aggregates or change a sink ceiling through a control that does not exist. Actual execution or write failures still need repair or an honest failure report.",
].join("\n\n");
